"use client";

import { Renderer, type Spec } from "@json-render/react";
import { registry } from "@/lib/jsonui/registry";
import { JsonUiProvider } from "@/components/JsonUiProvider";

/**
 * Design-contract storyboard for ticket #26.
 *
 * Renders two representative specs through the real catalog registry:
 *  1. Answer layout – the centred, prose-shaped view generated by /api/generate.
 *  2. Home-section layout – the full-width section view used by homeSpec.ts.
 *
 * The specs use mock corpus state so the storyboard is self-contained and
 * runnable without a backend. It is the visual companion to
 * docs/design-contract.md.
 */

const mockState = {
  corpus: {
    skills: [
      {
        category: "Programming Languages",
        skills: [
          { name: "TypeScript", lightImage: "/Noah Icon FA.svg", darkImage: "/Noah Icon FA.svg" },
          { name: "Python", lightImage: "/Noah Icon FA.svg", darkImage: "/Noah Icon FA.svg" },
          { name: "Ruby", lightImage: "/Noah Icon FA.svg", darkImage: "/Noah Icon FA.svg" },
        ],
      },
      {
        category: "Infrastructure",
        skills: [
          { name: "Docker", lightImage: "/Noah Icon FA.svg", darkImage: "/Noah Icon FA.svg" },
          { name: "AWS", lightImage: "/Noah Icon FA.svg", darkImage: "/Noah Icon FA.svg" },
        ],
      },
    ],
    careerTimeline: [
      {
        company: "Supa",
        role: "Full-Stack Developer",
        period: "2020 - Present",
        logo: "/Noah Icon FA.svg",
        url: "https://supa.so",
      },
      {
        company: "Bowiq",
        role: "CAD Designer & 3D Printing Engineer",
        period: "2023 - Present",
        logo: "/Noah Icon FA.svg",
        url: "https://bowiq.com",
      },
    ],
    projects: [
      {
        slug: "ai-image-cutout",
        title: "AI Image Cutout Tool",
        description: "A fun little app that uses segment-anything to cut people and objects out of images.",
        image: "/cutout_project.jpeg",
        url: "https://github.com/OriginalByteMe/AI_Image_cutout_maker",
        technologies: [
          { name: "Python", lightIcon: "/Noah Icon FA.svg", darkIcon: "/Noah Icon FA.svg" },
          { name: "AWS", lightIcon: "/Noah Icon FA.svg", darkIcon: "/Noah Icon FA.svg" },
        ],
      },
    ],
    contact: {
      email: "noahrijkaard@gmail.com",
      github: "https://github.com/OriginalByteMe",
      linkedin: "https://www.linkedin.com/in/noah-rijkaard/",
    },
  },
};

const initialState = {
  "/corpus/skills": mockState.corpus.skills,
  "/corpus/careerTimeline": mockState.corpus.careerTimeline,
  "/corpus/projects": mockState.corpus.projects,
  "/corpus/contact": mockState.corpus.contact,
};

const answerSpec: Spec = {
  root: "root",
  elements: {
    root: {
      type: "Stack",
      props: { gap: "md" },
      children: ["heading", "intro", "skills", "callout", "stat"],
    },
    heading: {
      type: "Heading",
      props: { text: "What is your tech stack?", level: 1 },
      children: [],
    },
    intro: {
      type: "Prose",
      props: {
        text: "I work across the full stack, but I’m most productive in TypeScript and Python ecosystems. Infrastructure-wise I live in Docker, AWS, and Terraform.",
      },
      children: [],
    },
    skills: {
      type: "SkillCloud",
      props: { statePath: "/corpus/skills" },
      children: [],
    },
    callout: {
      type: "Callout",
      props: {
        text: "I prefer boring, reliable tools until the problem genuinely calls for something exotic.",
        tone: "info",
      },
      children: [],
    },
    stat: {
      type: "StatCallout",
      props: { value: "5+", label: "Years shipping production code" },
      children: [],
    },
  },
};

const homeSectionSpec: Spec = {
  root: "root",
  elements: {
    root: {
      type: "Section",
      props: { title: "About Me" },
      children: ["aboutProse", "aboutColumns"],
    },
    aboutProse: {
      type: "Prose",
      props: {
        text: "I’m a passionate developer with a keen eye for design and a love for creating efficient, scalable solutions.",
      },
      children: [],
    },
    aboutColumns: {
      type: "Columns",
      props: { count: 2 },
      children: ["skillGrid", "careerTimeline"],
    },
    skillGrid: {
      type: "SkillGrid",
      props: { statePath: "/corpus/skills" },
      children: [],
    },
    careerTimeline: {
      type: "CareerTimeline",
      props: { statePath: "/corpus/careerTimeline" },
      children: [],
    },
  },
};

export function DesignContractStoryboard() {
  return (
    <JsonUiProvider initialState={initialState}>
      <div className="relative min-h-screen overflow-hidden">
        {/* A subdued placeholder background so the frosted-glass surfaces read clearly. */}
        <div className="absolute inset-0 bg-gradient-to-br from-blue-900/40 via-slate-900 to-blue-950" />

        <div className="relative z-10 space-y-8 py-12">
          <header className="container mx-auto px-4">
            <h1 className="text-3xl font-bold text-white">Design Contract Storyboard (#26)</h1>
            <p className="mt-2 text-gray-300">
              Companion prototype for{" "}
              <code className="rounded bg-white/10 px-1.5 py-0.5 text-sm">docs/design-contract.md</code>.
            </p>
          </header>

          {/* Answer layout demo */}
          <section className="relative">
            <div className="container mx-auto px-4 pb-4">
              <h2 className="text-sm font-semibold uppercase tracking-wide text-gray-400">Answer layout</h2>
              <p className="text-sm text-gray-500">Centred reading column (max-w-3xl) — the shape /api/generate should emit.</p>
            </div>
            <div className="mx-auto w-full max-w-3xl px-4 py-16">
              <Renderer spec={answerSpec} registry={registry} />
            </div>
          </section>

          {/* Home-section layout demo */}
          <section className="relative">
            <div className="container mx-auto px-4 pb-4">
              <h2 className="text-sm font-semibold uppercase tracking-wide text-gray-400">Home-section layout</h2>
              <p className="text-sm text-gray-500">Full-width section with container — the shape homeSpec.ts emits.</p>
            </div>
            <Renderer spec={homeSectionSpec} registry={registry} />
          </section>
        </div>
      </div>
    </JsonUiProvider>
  );
}

export default DesignContractStoryboard;
